<?php

namespace App\Console\Commands;

use App\Services\Social\SocialCard;
use Illuminate\Console\Command;

/**
 * Answers the one question that decides whether cards work on a given host:
 * is there a TrueType font on it?
 *
 * The brand faces are served from a font CDN rather than vendored, so cards are
 * drawn with whichever system face resolves. Without one, the site silently
 * serves the old static image — correct behaviour, but invisible. This makes it
 * visible in one command, and writes a sample so the result can be looked at
 * rather than trusted.
 */
class SocialDoctorCommand extends Command
{
    protected $signature = 'social:doctor {--out= : Write a sample card to this path}';

    protected $description = 'Report whether social preview cards can be drawn on this host, and write a sample';

    public function handle(SocialCard $cards): int
    {
        $this->line('GD extension:        '.(extension_loaded('gd') ? 'present' : 'MISSING'));
        $this->line('TrueType support:    '.(function_exists('imagettftext') ? 'present' : 'MISSING'));

        foreach (['bold', 'regular'] as $weight) {
            $font = $cards->font($weight);
            $this->line(str_pad(ucfirst($weight).' face:', 21).($font ?? 'NOT FOUND'));
        }

        if (! $cards->available()) {
            $this->error('Cards cannot be drawn here; every page will serve the static image instead.');
            $this->line('Install a font package (fonts-dejavu-core on Debian and Ubuntu), or point');
            $this->line('SOCIAL_FONT_BOLD and SOCIAL_FONT_REGULAR at .ttf files on this host.');

            return self::FAILURE;
        }

        $path = $cards->render('doctor-sample', [
            'eyebrow' => config('aipolicytracker.site_name'),
            'title' => 'A sample card drawn on this host',
            'meta' => 'If you can read this, previews will render for every record.',
            'footer' => 'Generated by social:doctor · '.now()->toDayDateTimeString(),
        ]);

        $this->info('Cards can be drawn. Sample written to the '.config('social.cache_disk').' disk at '.$path);

        if ($out = $this->option('out')) {
            file_put_contents($out, \Illuminate\Support\Facades\Storage::disk(config('social.cache_disk'))->get($path));
            $this->line('Copied to '.$out);
        }

        return self::SUCCESS;
    }
}
