<?php

namespace App\Http\Controllers\Site;

use App\Http\Controllers\Controller;
use App\Models\ChangeEvent;
use App\Models\Deadline;
use App\Models\Obligation;
use App\Models\TaxonomyTerm;
use App\Support\Seo;
use Illuminate\View\View;

/**
 * Audience pages: the corpus cut by role, sector or use case. Editorial text
 * orients; the duties, controls, evidence, dates and changes are the live
 * records that carry the matching taxonomy term, so the page is regenerated by
 * every import rather than rewritten by hand. A cut with fewer than five duties
 * is served but not indexed: it would be a thin page with a confident title.
 */
class AudienceController extends Controller
{
    public const MIN_INDEXABLE_DUTIES = 5;

    public function index(): View
    {
        $pages = collect(config('content.audiences'))->map(function (array $page, string $slug) {
            $count = $this->duties($page)->count();

            return $page + ['slug' => $slug, 'duties' => $count, 'url' => route('audiences.show', $slug)];
        })->values();

        $seo = Seo::make(
            'AI regulation by role, sector and use case',
            'The recorded AI duties, the controls that meet them and the evidence to keep, cut by who you are: provider, deployer, public body, and by sector and use case such as hiring, healthcare, finance and generative AI.',
            route('audiences.index')
        )->withBreadcrumbs([['Home', route('home')], ['By role and sector', route('audiences.index')]])
            ->withPageType('CollectionPage', ['mainEntity' => Seo::itemList($pages, fn ($p) => $p['h1'], fn ($p) => $p['url'], 'Audience pages')]);

        return view('site.audiences.index', compact('seo', 'pages'));
    }

    public function show(string $audience): View
    {
        $page = config('content.audiences.'.$audience);
        abort_unless($page, 404);
        $term = TaxonomyTerm::where('taxonomy', $page['taxonomy'])->where('slug', $page['term'])->first();

        $duties = $this->duties($page)->with(['policyInstrument.jurisdiction', 'controls.evidence'])->orderByDesc('is_binding')->orderBy('title')->get()
            ->filter(fn ($o) => $o->policyInstrument?->published_at);
        $byJurisdiction = $duties->groupBy(fn ($o) => $o->policyInstrument->jurisdiction->name)->sortKeys();
        $instruments = $duties->pluck('policyInstrument')->unique('id')->sortBy('title')->values();
        $jurisdictions = $instruments->pluck('jurisdiction')->unique('id')->sortBy('name')->values();

        // Controls, counted by how many of these duties each one serves, so the ones
        // worth building first sort to the top.
        $controls = $duties->flatMap(fn ($o) => $o->controls->filter(fn ($c) => $c->published_at)->map(fn ($c) => ['control' => $c, 'relationship' => $c->pivot->relationship, 'obligation' => $o]))
            ->groupBy(fn ($row) => $row['control']->slug)
            ->map(fn ($rows) => ['control' => $rows->first()['control'], 'satisfies' => $rows->where('relationship', 'satisfies')->count(), 'supports' => $rows->where('relationship', 'supports')->count(), 'duties' => $rows->count()])
            ->sortByDesc(fn ($r) => [$r['satisfies'], $r['duties']])->values();
        $evidence = $controls->flatMap(fn ($r) => $r['control']->evidence)->unique('title')->sortBy('title')->values();
        $evidenceTypes = TaxonomyTerm::where('taxonomy', 'evidence_type')->pluck('name', 'slug');

        $deadlines = Deadline::with('policyInstrument.jurisdiction')->whereIn('policy_instrument_id', $instruments->pluck('id'))->whereNotNull('due_on')->where('due_on', '>=', now()->toDateString())->orderBy('due_on')->limit(6)->get();
        $changes = ChangeEvent::published()->with(['jurisdiction', 'policyInstrument'])->whereIn('policy_instrument_id', $instruments->pluck('id'))->orderByDesc('occurred_on')->limit(5)->get();
        $indexable = $duties->count() >= self::MIN_INDEXABLE_DUTIES;
        $modified = collect([$duties->max('updated_at'), $controls->max(fn ($r) => $r['control']->updated_at)])->filter()->max();

        $seo = Seo::make($page['title'], $page['description'], route('audiences.show', $audience), $indexable)
            ->withBreadcrumbs([['Home', route('home')], ['By role and sector', route('audiences.index')], [$page['h1'], route('audiences.show', $audience)]])
            ->withModified($modified)
            ->withOgType('article')
            ->withPageType('Article', [
                'headline' => $page['h1'],
                'author' => ['@id' => url('/').'#organization'],
                'about' => $term ? ['@type' => 'DefinedTerm', 'name' => $term->name, 'inDefinedTermSet' => route('obligations.index')] : null,
                'mentions' => $instruments->map(fn ($p) => ['@type' => $p->is_binding ? 'Legislation' : 'CreativeWork', 'name' => $p->short_title ?: $p->title, 'url' => $p->url()])->values()->all(),
            ])
            ->withFaq($page['faq'] ?? []);

        return view('site.audiences.show', compact('seo', 'page', 'audience', 'term', 'duties', 'byJurisdiction', 'instruments', 'jurisdictions', 'controls', 'evidence', 'evidenceTypes', 'deadlines', 'changes', 'indexable'));
    }

    /** The published duties carrying this audience's taxonomy term. */
    private function duties(array $page)
    {
        return Obligation::published()->withTerm($page['taxonomy'], $page['term']);
    }
}
