<?php

use App\Enums\PolicyStatus;

// OpenAPI 3.1 description of the read-only public API. Served at /openapi.json.
$base = url('/api/v1');
$sourceQuality = [
    'type' => 'object',
    'properties' => [
        'official_source_url' => ['type' => ['string', 'null'], 'format' => 'uri'],
        'source_title' => ['type' => ['string', 'null']],
        'source_publisher' => ['type' => ['string', 'null']],
        'source_document_date' => ['type' => ['string', 'null'], 'format' => 'date'],
        'source_reference' => ['type' => ['string', 'null']],
        'source_tier' => ['type' => 'integer', 'minimum' => 1, 'maximum' => 4],
        'last_checked_at' => ['type' => ['string', 'null'], 'format' => 'date'],
        'last_verified_at' => ['type' => ['string', 'null'], 'format' => 'date'],
        'review_status' => ['type' => 'string', 'enum' => ['draft', 'pending_review', 'verified', 'needs_update']],
        'confidence_level' => ['type' => 'string', 'enum' => ['high', 'medium', 'low', 'unavailable']],
        'content_version' => ['type' => 'integer'],
        'change_summary' => ['type' => ['string', 'null']],
        'reviewed_by' => ['type' => ['string', 'null']],
    ],
];
$pagination = ['type' => 'object', 'properties' => ['total' => ['type' => 'integer'], 'per_page' => ['type' => 'integer'], 'current_page' => ['type' => 'integer'], 'last_page' => ['type' => 'integer']]];
// The mirrored datasets add the filters applied and the upstream attribution,
// which is a licence condition on reusing their rows.
$externalMeta = ['type' => 'object', 'properties' => $pagination['properties'] + [
    'filters' => ['type' => 'object', 'description' => 'The filters applied, as parsed; unrecognised values are null.'],
    'source' => ['type' => 'object', 'description' => 'The upstream dataset, its licence and how to cite it.', 'properties' => ['name' => ['type' => 'string'], 'url' => ['type' => 'string', 'format' => 'uri'], 'license' => ['type' => 'string'], 'license_url' => ['type' => 'string', 'format' => 'uri'], 'citation' => ['type' => 'string'], 'snapshot_date' => ['type' => 'string', 'format' => 'date']]],
]];
$links = ['type' => 'object', 'properties' => ['next' => ['type' => ['string', 'null'], 'format' => 'uri'], 'prev' => ['type' => ['string', 'null'], 'format' => 'uri']]];
$changesMeta = ['type' => 'object', 'properties' => $pagination['properties'] + ['license' => ['type' => 'string'], 'license_url' => ['type' => 'string', 'format' => 'uri']]];
$changesLinks = ['type' => 'object', 'properties' => $links['properties'] + ['rss' => ['type' => 'string', 'format' => 'uri']]];
$filterParams = [
    ['name' => 'q', 'in' => 'query', 'schema' => ['type' => 'string'], 'description' => 'Keyword search'],
    ['name' => 'jurisdiction', 'in' => 'query', 'schema' => ['type' => 'string'], 'description' => 'Comma-separated jurisdiction slugs'],
    ['name' => 'status', 'in' => 'query', 'schema' => ['type' => 'string'], 'description' => 'Comma-separated policy statuses'],
    ['name' => 'type', 'in' => 'query', 'schema' => ['type' => 'string'], 'description' => 'Comma-separated instrument types'],
    ['name' => 'sector', 'in' => 'query', 'schema' => ['type' => 'string']],
    ['name' => 'use_case', 'in' => 'query', 'schema' => ['type' => 'string']],
    ['name' => 'risk', 'in' => 'query', 'schema' => ['type' => 'string']],
    ['name' => 'actor', 'in' => 'query', 'schema' => ['type' => 'string']],
    ['name' => 'binding', 'in' => 'query', 'schema' => ['type' => 'string', 'enum' => ['yes', 'no']]],
    ['name' => 'sort', 'in' => 'query', 'schema' => ['type' => 'string', 'enum' => ['updated', 'effective', 'relevance', 'jurisdiction']]],
    ['name' => 'page', 'in' => 'query', 'schema' => ['type' => 'integer']],
    ['name' => 'per_page', 'in' => 'query', 'schema' => ['type' => 'integer', 'maximum' => 100]],
];

return [
    'openapi' => '3.1.0',
    'info' => [
        'title' => config('aipolicytracker.site_name').' public API',
        'version' => '1.0.0',
        'summary' => 'Read-only access to source-backed AI policy records.',
        'description' => 'Open, source-backed AI policy and regulatory intelligence. All records carry an official source URL, review status, confidence level and verification dates. Data licence: '.config('aipolicytracker.data_license').'. Informational only; not legal advice.',
        'license' => ['name' => config('aipolicytracker.data_license'), 'url' => config('aipolicytracker.data_license_url')],
        'termsOfService' => route('methodology'),
        'contact' => ['name' => config('aipolicytracker.site_name'), 'email' => config('aipolicytracker.contact_email'), 'url' => route('about')],
    ],
    'servers' => [['url' => $base]],
    'paths' => [
        '/' => ['get' => ['summary' => 'API root and endpoint index', 'operationId' => 'root', 'responses' => ['200' => ['description' => 'Endpoint index']]]],
        '/jurisdictions' => ['get' => ['summary' => 'List published jurisdictions', 'operationId' => 'listJurisdictions', 'responses' => ['200' => ['description' => 'Jurisdictions', 'content' => ['application/json' => ['schema' => ['type' => 'object', 'properties' => ['data' => ['type' => 'array', 'items' => ['$ref' => '#/components/schemas/Jurisdiction']]]]]]]]]],
        '/jurisdictions/{slug}' => ['get' => ['summary' => 'Get a jurisdiction with its policies', 'operationId' => 'getJurisdiction', 'parameters' => [['name' => 'slug', 'in' => 'path', 'required' => true, 'schema' => ['type' => 'string']]], 'responses' => ['200' => ['description' => 'Jurisdiction'], '404' => ['description' => 'Not found']]]],
        '/policies' => ['get' => ['summary' => 'Search and filter policy instruments', 'operationId' => 'listPolicies', 'parameters' => $filterParams, 'responses' => ['200' => ['description' => 'Paginated policies', 'content' => ['application/json' => ['schema' => ['type' => 'object', 'properties' => ['data' => ['type' => 'array', 'items' => ['$ref' => '#/components/schemas/PolicySummary']], 'meta' => $pagination]]]]]]]],
        '/policies/{slug}' => ['get' => ['summary' => 'Get a full policy record', 'operationId' => 'getPolicy', 'parameters' => [['name' => 'slug', 'in' => 'path', 'required' => true, 'schema' => ['type' => 'string']]], 'responses' => ['200' => ['description' => 'Policy', 'content' => ['application/json' => ['schema' => ['type' => 'object', 'properties' => ['data' => ['$ref' => '#/components/schemas/Policy']]]]]], '404' => ['description' => 'Not found']]]],
        '/obligations' => ['get' => ['summary' => 'Search and filter obligations', 'operationId' => 'listObligations', 'parameters' => array_merge($filterParams, [['name' => 'category', 'in' => 'query', 'schema' => ['type' => 'string'], 'description' => 'Obligation category slug']]), 'responses' => ['200' => ['description' => 'Paginated obligations']]]],
        '/controls' => ['get' => ['summary' => 'List the controls an organisation operates to meet AI duties, each with the duties it serves, its evidence and its standards references', 'operationId' => 'listControls', 'parameters' => [['name' => 'kind', 'in' => 'query', 'schema' => ['type' => 'string', 'enum' => ['policy', 'process', 'technical', 'contractual', 'training']]], ['name' => 'framework', 'in' => 'query', 'schema' => ['type' => 'string'], 'description' => 'Framework key, e.g. iso_42001 or nist_ai_rmf']], 'responses' => ['200' => ['description' => 'Controls']]]],
        '/controls/{slug}' => ['get' => ['summary' => 'Get one control with every duty it satisfies or supports', 'operationId' => 'getControl', 'parameters' => [['name' => 'slug', 'in' => 'path', 'required' => true, 'schema' => ['type' => 'string']]], 'responses' => ['200' => ['description' => 'Control'], '404' => ['description' => 'Not found']]]],
        '/obligations/{slug}' => ['get' => ['summary' => 'Get an obligation', 'operationId' => 'getObligation', 'parameters' => [['name' => 'slug', 'in' => 'path', 'required' => true, 'schema' => ['type' => 'string']]], 'responses' => ['200' => ['description' => 'Obligation'], '404' => ['description' => 'Not found']]]],
        '/changes' => ['get' => ['summary' => 'List change events (newest first)', 'operationId' => 'listChanges', 'parameters' => [['name' => 'since', 'in' => 'query', 'schema' => ['type' => 'string', 'format' => 'date']], ['name' => 'jurisdiction', 'in' => 'query', 'schema' => ['type' => 'string']], ['name' => 'page', 'in' => 'query', 'schema' => ['type' => 'integer']]], 'responses' => ['200' => ['description' => 'Paginated change events', 'content' => ['application/json' => ['schema' => ['type' => 'object', 'properties' => ['data' => ['type' => 'array', 'items' => ['$ref' => '#/components/schemas/ChangeEvent']], 'meta' => $changesMeta, 'links' => $changesLinks]]]]]]]],
        '/taxonomies' => ['get' => ['summary' => 'Controlled vocabularies', 'operationId' => 'listTaxonomies', 'responses' => ['200' => ['description' => 'Taxonomy terms grouped by taxonomy']]]],
        '/frameworks' => ['get' => ['summary' => 'Frameworks that legal duties are crosswalked to, with coverage counts', 'operationId' => 'listFrameworks', 'responses' => ['200' => ['description' => 'Frameworks with the number of duties mapped to each']]]],
        '/frameworks/{framework}' => ['get' => ['summary' => 'One framework, with its mapped duties grouped by clause or function', 'operationId' => 'getFramework', 'parameters' => [['name' => 'framework', 'in' => 'path', 'required' => true, 'schema' => ['type' => 'string'], 'description' => 'Framework slug, e.g. iso-42001 or nist-ai-rmf']], 'responses' => ['200' => ['description' => 'Framework with grouped mappings'], '404' => ['description' => 'Unknown framework, or one with no mappings']]]],
        '/frameworks/{framework}/{jurisdiction}' => ['get' => ['summary' => "One jurisdiction's duties mapped to one framework", 'operationId' => 'getFrameworkCrosswalk', 'parameters' => [['name' => 'framework', 'in' => 'path', 'required' => true, 'schema' => ['type' => 'string']], ['name' => 'jurisdiction', 'in' => 'path', 'required' => true, 'schema' => ['type' => 'string']]], 'responses' => ['200' => ['description' => 'Crosswalk rows, with obligations_mapped against obligations_recorded'], '404' => ['description' => 'Unknown pair, or one with no mappings']]]],
        '/deadlines' => ['get' => ['summary' => 'Compliance dates recorded against instruments and duties', 'operationId' => 'listDeadlines', 'parameters' => [['name' => 'from', 'in' => 'query', 'schema' => ['type' => 'string', 'format' => 'date']], ['name' => 'page', 'in' => 'query', 'schema' => ['type' => 'integer']]], 'responses' => ['200' => ['description' => 'Paginated deadlines']]]],
        '/deadlines/applicable' => ['post' => ['summary' => 'Which recorded dates apply to one organisation, and why', 'operationId' => 'applicableDeadlines', 'description' => 'The deadline engine: recorded deadlines filtered by the scope recorded on their instrument and duty (role, system type, risk tier, sector, use case). A filter, not a legal determination. The same answers as a query string on /deadlines/applicable.ics return an iCalendar file.', 'requestBody' => ['required' => true, 'content' => ['application/json' => ['schema' => ['type' => 'object', 'required' => ['jurisdictions'], 'properties' => ['jurisdictions' => ['type' => 'array', 'minItems' => 1, 'maxItems' => 8, 'items' => ['type' => 'string']], 'role' => ['type' => ['string', 'null'], 'description' => 'An actor slug: provider, deployer, importer, distributor, gpai_provider, public_authority…'], 'system_types' => ['type' => 'array', 'items' => ['type' => 'string']], 'risk' => ['type' => ['string', 'null']], 'sectors' => ['type' => 'array', 'items' => ['type' => 'string']], 'use_cases' => ['type' => 'array', 'items' => ['type' => 'string']]]]]]], 'responses' => ['200' => ['description' => 'The applicable deadlines', 'content' => ['application/json' => ['schema' => ['type' => 'object', 'properties' => ['data' => ['type' => 'array', 'items' => ['$ref' => '#/components/schemas/ApplicableDeadline']], 'meta' => ['type' => 'object', 'properties' => ['total' => ['type' => 'integer'], 'answers' => ['type' => 'object'], 'ics_url' => ['type' => 'string', 'format' => 'uri'], 'page_url' => ['type' => 'string', 'format' => 'uri'], 'license' => ['type' => 'string'], 'license_url' => ['type' => 'string', 'format' => 'uri'], 'disclaimer' => ['type' => 'string']]]]]]]], '422' => ['description' => 'No jurisdiction given']]]],
        '/deadlines/applicable.ics' => ['get' => ['summary' => 'The applicable deadlines as an iCalendar file', 'operationId' => 'applicableDeadlinesIcs', 'parameters' => [['name' => 'jurisdictions[]', 'in' => 'query', 'required' => true, 'schema' => ['type' => 'array', 'items' => ['type' => 'string']]], ['name' => 'role', 'in' => 'query', 'schema' => ['type' => 'string']], ['name' => 'risk', 'in' => 'query', 'schema' => ['type' => 'string']]], 'responses' => ['200' => ['description' => 'text/calendar'], '404' => ['description' => 'No jurisdiction given']]]],
        '/incidents' => ['get' => ['summary' => 'Incidents mirrored from the AI Incident Database', 'operationId' => 'listIncidents', 'description' => 'Responses carry the upstream source, licence and citation in meta.source; reusing the rows carries that attribution requirement with them.', 'parameters' => [['name' => 'domain', 'in' => 'query', 'schema' => ['type' => 'string']], ['name' => 'country', 'in' => 'query', 'schema' => ['type' => 'string']], ['name' => 'from', 'in' => 'query', 'schema' => ['type' => 'string', 'format' => 'date']], ['name' => 'per_page', 'in' => 'query', 'schema' => ['type' => 'integer']], ['name' => 'page', 'in' => 'query', 'schema' => ['type' => 'integer']]], 'responses' => ['200' => ['description' => 'Paginated incidents with source attribution', 'content' => ['application/json' => ['schema' => ['type' => 'object', 'properties' => ['data' => ['type' => 'array', 'items' => ['$ref' => '#/components/schemas/Incident']], 'meta' => $externalMeta, 'links' => $links]]]]]]]],
        '/risks' => ['get' => ['summary' => 'Risk entries mirrored from the MIT AI Risk Repository', 'operationId' => 'listRisks', 'description' => 'Responses carry the upstream source, licence and citation in meta.source; reusing the rows carries that attribution requirement with them.', 'parameters' => [['name' => 'domain', 'in' => 'query', 'schema' => ['type' => 'integer']], ['name' => 'entity', 'in' => 'query', 'schema' => ['type' => 'string']], ['name' => 'intent', 'in' => 'query', 'schema' => ['type' => 'string']], ['name' => 'timing', 'in' => 'query', 'schema' => ['type' => 'string']], ['name' => 'per_page', 'in' => 'query', 'schema' => ['type' => 'integer']], ['name' => 'page', 'in' => 'query', 'schema' => ['type' => 'integer']]], 'responses' => ['200' => ['description' => 'Paginated risk entries with source attribution', 'content' => ['application/json' => ['schema' => ['type' => 'object', 'properties' => ['data' => ['type' => 'array', 'items' => ['$ref' => '#/components/schemas/RiskEntry']], 'meta' => $externalMeta, 'links' => $links]]]]]]]],
        '/templates' => ['get' => ['summary' => 'The templates library: generated XLSX/DOCX files, versioned', 'operationId' => 'listTemplates', 'description' => 'Every template is generated from the recorded duties, controls, deadlines and crosswalks and rebuilt when the records change. Files are free (CC BY 4.0) and need no account.', 'parameters' => [['name' => 'type', 'in' => 'query', 'schema' => ['type' => 'string']], ['name' => 'topic', 'in' => 'query', 'schema' => ['type' => 'string']], ['name' => 'framework', 'in' => 'query', 'schema' => ['type' => 'string']]], 'responses' => ['200' => ['description' => 'Templates with their latest version', 'content' => ['application/json' => ['schema' => ['type' => 'object', 'properties' => ['data' => ['type' => 'array', 'items' => ['$ref' => '#/components/schemas/Template']], 'meta' => ['type' => 'object', 'properties' => ['total' => ['type' => 'integer'], 'filters' => ['type' => 'object'], 'types' => ['type' => 'object'], 'topics' => ['type' => 'object'], 'frameworks' => ['type' => 'object'], 'license' => ['type' => 'string'], 'license_url' => ['type' => 'string', 'format' => 'uri'], 'disclaimer' => ['type' => 'string']]]]]]]]]]],
        '/templates/{slug}' => ['get' => ['summary' => 'One template: what it covers, every version, the covered duties', 'operationId' => 'getTemplate', 'parameters' => [['name' => 'slug', 'in' => 'path', 'required' => true, 'schema' => ['type' => 'string']]], 'responses' => ['200' => ['description' => 'The template', 'content' => ['application/json' => ['schema' => ['type' => 'object', 'properties' => ['data' => ['$ref' => '#/components/schemas/TemplateDetail'], 'meta' => ['type' => 'object', 'properties' => ['license' => ['type' => 'string'], 'license_url' => ['type' => 'string', 'format' => 'uri'], 'disclaimer' => ['type' => 'string']]]]]]]], '404' => ['description' => 'Unknown template']]]],
        '/templates/{slug}/download' => ['get' => ['summary' => 'Redirects to the latest file in the requested format', 'operationId' => 'downloadTemplate', 'parameters' => [['name' => 'slug', 'in' => 'path', 'required' => true, 'schema' => ['type' => 'string']], ['name' => 'format', 'in' => 'query', 'schema' => ['type' => 'string', 'enum' => ['xlsx', 'docx']]]], 'responses' => ['302' => ['description' => 'Redirect to the file'], '404' => ['description' => 'Unknown template or format']]]],
    ],
    'components' => [
        'schemas' => [
            'SourceQuality' => $sourceQuality,
            'Jurisdiction' => ['type' => 'object', 'properties' => ['slug' => ['type' => 'string'], 'name' => ['type' => 'string'], 'iso_code' => ['type' => ['string', 'null']], 'jurisdiction_type' => ['type' => 'string'], 'region' => ['type' => ['string', 'null']], 'overview' => ['type' => ['string', 'null']], 'regulatory_status_summary' => ['type' => ['string', 'null']], 'regulators' => ['type' => 'array', 'items' => ['type' => 'object']], 'official_sources' => ['type' => 'array', 'items' => ['type' => 'object']], 'url' => ['type' => 'string', 'format' => 'uri'], 'source' => ['$ref' => '#/components/schemas/SourceQuality']]],
            'PolicySummary' => ['type' => 'object', 'properties' => ['slug' => ['type' => 'string'], 'title' => ['type' => 'string'], 'short_title' => ['type' => ['string', 'null']], 'jurisdiction' => ['type' => 'string'], 'instrument_type' => ['type' => 'string'], 'status' => ['type' => 'string', 'enum' => PolicyStatus::values()], 'is_binding' => ['type' => 'boolean'], 'summary_plain' => ['type' => ['string', 'null']], 'applies_from' => ['type' => ['string', 'null'], 'format' => 'date'], 'official_source_url' => ['type' => ['string', 'null'], 'format' => 'uri'], 'last_verified_at' => ['type' => ['string', 'null'], 'format' => 'date'], 'review_status' => ['type' => 'string'], 'confidence_level' => ['type' => 'string'], 'url' => ['type' => 'string', 'format' => 'uri']]],
            'Policy' => ['allOf' => [['$ref' => '#/components/schemas/PolicySummary'], ['type' => 'object', 'properties' => ['scope_summary' => ['type' => ['string', 'null']], 'who_it_applies_to' => ['type' => ['string', 'null']], 'sections' => ['type' => 'array', 'items' => ['type' => 'object']], 'obligations' => ['type' => 'array', 'items' => ['$ref' => '#/components/schemas/Obligation']], 'deadlines' => ['type' => 'array', 'items' => ['type' => 'object']], 'sources' => ['type' => 'array', 'items' => ['type' => 'object']], 'faq' => ['type' => 'array', 'items' => ['type' => 'object']], 'source' => ['$ref' => '#/components/schemas/SourceQuality']]]]],
            'ChangeEvent' => ['type' => 'object', 'required' => ['slug', 'occurred_on', 'title', 'url', 'significance'], 'properties' => ['slug' => ['type' => 'string'], 'occurred_on' => ['type' => 'string', 'format' => 'date', 'description' => 'When the change happened.'], 'jurisdiction' => ['type' => ['string', 'null']], 'policy' => ['type' => ['string', 'null']], 'title' => ['type' => 'string'], 'what_changed' => ['type' => ['string', 'null']], 'practical_impact' => ['type' => ['string', 'null']], 'impact_level' => ['type' => 'string', 'enum' => ['urgent', 'high', 'routine']], 'status_after' => ['type' => ['string', 'null']], 'significance' => ['type' => 'integer', 'minimum' => 0, 'maximum' => 100, 'description' => 'How much the change matters by a published, versioned rule: impact level, binding force, status after, review state and recency. Drives "top stories" on the updates pages.'], 'first_published_at' => ['type' => ['string', 'null'], 'format' => 'date-time', 'description' => 'When the entry first appeared on this site.'], 'url' => ['type' => 'string', 'format' => 'uri'], 'source' => ['$ref' => '#/components/schemas/SourceQuality']]],
            'Incident' => ['type' => 'object', 'required' => ['incident_id', 'slug', 'title', 'url'], 'properties' => ['incident_id' => ['type' => 'integer', 'description' => 'The AI Incident Database number; cite the record as incidentdatabase.ai/cite/{incident_id}.'], 'slug' => ['type' => 'string', 'description' => 'Readable address of the page on this site. Assigned once and never changed; the numeric address redirects to it.'], 'title' => ['type' => 'string'], 'description' => ['type' => ['string', 'null']], 'occurred_on' => ['type' => ['string', 'null'], 'format' => 'date'], 'domain' => ['type' => ['string', 'null']], 'subdomain' => ['type' => ['string', 'null']], 'entity' => ['type' => ['string', 'null']], 'intent' => ['type' => ['string', 'null']], 'timing' => ['type' => ['string', 'null']], 'sectors' => ['type' => ['array', 'null']], 'countries' => ['type' => ['array', 'null']], 'deployers' => ['type' => ['array', 'null']], 'developers' => ['type' => ['array', 'null']], 'harmed' => ['type' => ['array', 'null']], 'report_count' => ['type' => ['integer', 'null']], 'harm_domain' => ['type' => ['string', 'null'], 'description' => 'The MIT AI Risk Repository domain the record is coded to, as a slug.'], 'sensitivity' => ['type' => 'string', 'enum' => ['standard', 'sensitive'], 'description' => 'sensitive: the record concerns sexual imagery; its title and description are neutral and the page is not offered to search engines. Do not repeat the source headline.'], 'policy_angle' => ['type' => ['string', 'null'], 'description' => 'One neutral sentence from the record\'s coding: the harm domain and how many recorded laws address it where it happened.'], 'related_policies' => ['type' => 'array', 'description' => 'Recorded instruments addressing this harm where it happened, binding first; a reviewer may have set the list.', 'items' => ['type' => 'object', 'properties' => ['slug' => ['type' => 'string'], 'title' => ['type' => 'string'], 'jurisdiction' => ['type' => ['string', 'null']], 'url' => ['type' => 'string', 'format' => 'uri']]]], 'url' => ['type' => 'string', 'format' => 'uri']]],
            'RiskEntry' => ['type' => 'object', 'required' => ['ev_id', 'slug', 'url'], 'properties' => ['ev_id' => ['type' => 'string', 'description' => 'The MIT AI Risk Repository evidence code.'], 'slug' => ['type' => 'string', 'description' => 'Readable address of the page on this site. Assigned once and never changed; the evidence-code address redirects to it.'], 'risk_category' => ['type' => ['string', 'null']], 'risk_subcategory' => ['type' => ['string', 'null']], 'description' => ['type' => ['string', 'null']], 'domain' => ['type' => ['integer', 'null'], 'description' => 'MIT risk domain number, 1–7.'], 'subdomain' => ['type' => ['string', 'null']], 'entity' => ['type' => ['string', 'null']], 'intent' => ['type' => ['string', 'null']], 'timing' => ['type' => ['string', 'null']], 'level' => ['type' => ['string', 'null']], 'paper' => ['type' => ['string', 'null'], 'description' => 'The repository\'s key for the source paper.'], 'citation' => ['type' => ['string', 'null'], 'description' => 'The source paper as author and year, e.g. "Hendrycks, 2023".'], 'paper_title' => ['type' => ['string', 'null']], 'url' => ['type' => 'string', 'format' => 'uri']]],
            'ApplicableDeadline' => ['type' => 'object', 'required' => ['title', 'status', 'jurisdiction', 'policy', 'why', 'matched_on'], 'properties' => ['title' => ['type' => 'string'], 'due_on' => ['type' => ['string', 'null'], 'format' => 'date'], 'date_precision' => ['type' => 'string'], 'date_label' => ['type' => ['string', 'null']], 'status' => ['type' => 'string'], 'confidence' => ['type' => 'string'], 'description' => ['type' => ['string', 'null']], 'jurisdiction' => ['type' => 'string'], 'policy' => ['type' => 'string'], 'obligation' => ['type' => ['string', 'null']], 'source_reference' => ['type' => ['string', 'null']], 'official_source_url' => ['type' => ['string', 'null']], 'why' => ['type' => 'array', 'items' => ['type' => 'string'], 'description' => 'Why the date is shown for these answers.'], 'matched_on' => ['type' => 'string', 'enum' => ['instrument', 'obligation']], 'originally' => ['type' => ['object', 'null'], 'description' => 'Set when a re-import found the date moved: the date first recorded.', 'properties' => ['due_on' => ['type' => ['string', 'null'], 'format' => 'date'], 'label' => ['type' => ['string', 'null']], 'changed_at' => ['type' => 'string', 'format' => 'date-time']]]]],
            'Template' => ['type' => 'object', 'required' => ['slug', 'title', 'type', 'formats', 'url'], 'properties' => ['slug' => ['type' => 'string'], 'title' => ['type' => 'string'], 'type' => ['type' => 'string', 'enum' => ['register', 'assessment', 'policy', 'procedure', 'checklist', 'crosswalk', 'kit']], 'formats' => ['type' => 'array', 'items' => ['type' => 'string', 'enum' => ['xlsx', 'docx']]], 'topics' => ['type' => 'array', 'items' => ['type' => 'string']], 'frameworks' => ['type' => 'array', 'items' => ['type' => 'string']], 'short' => ['type' => 'string'], 'covers' => ['type' => 'object', 'description' => 'Which duties the template covers: by obligation category, by instrument slug, or by framework.', 'properties' => ['categories' => ['type' => 'array', 'items' => ['type' => 'string']], 'policies' => ['type' => 'array', 'items' => ['type' => 'string']], 'frameworks' => ['type' => 'array', 'items' => ['type' => 'string']]]], 'version' => ['type' => ['integer', 'null'], 'description' => 'Latest built version; null until the first build.'], 'dataset_version' => ['type' => ['string', 'null'], 'description' => 'Hash of the record set the version was built from.'], 'generated_at' => ['type' => ['string', 'null'], 'format' => 'date-time'], 'citations' => ['type' => ['integer', 'null'], 'description' => 'Rows and paragraphs in the files that cite a record.'], 'downloads' => ['type' => 'integer'], 'files' => ['type' => 'array', 'items' => ['type' => 'object', 'properties' => ['format' => ['type' => 'string'], 'filename' => ['type' => 'string'], 'bytes' => ['type' => 'integer'], 'url' => ['type' => 'string', 'format' => 'uri']]]], 'url' => ['type' => 'string', 'format' => 'uri']]],
            'TemplateDetail' => ['allOf' => [['$ref' => '#/components/schemas/Template'], ['type' => 'object', 'properties' => ['inside' => ['type' => 'array', 'items' => ['type' => 'string']], 'legal_basis' => ['type' => 'array', 'items' => ['type' => 'string'], 'description' => 'Instrument and framework slugs the content is drawn from.'], 'caveat' => ['type' => ['string', 'null'], 'description' => '"dates" when the template copies dates a record notes may be superseded.'], 'covered_obligations' => ['type' => 'array', 'items' => ['type' => 'object', 'properties' => ['slug' => ['type' => 'string'], 'title' => ['type' => 'string'], 'policy' => ['type' => 'string'], 'source_reference' => ['type' => ['string', 'null']], 'url' => ['type' => 'string', 'format' => 'uri']]]], 'versions' => ['type' => 'array', 'items' => ['type' => 'object', 'properties' => ['version' => ['type' => 'integer'], 'generated_at' => ['type' => 'string', 'format' => 'date-time'], 'dataset_version' => ['type' => 'string'], 'changelog' => ['type' => ['string', 'null']], 'stats' => ['type' => ['object', 'null']]]]]]]]],
            'Obligation' => ['type' => 'object', 'properties' => ['slug' => ['type' => 'string'], 'title' => ['type' => 'string'], 'category' => ['type' => 'string'], 'summary' => ['type' => ['string', 'null']], 'practical_action' => ['type' => ['string', 'null']], 'is_binding' => ['type' => 'boolean'], 'applies_from' => ['type' => ['string', 'null'], 'format' => 'date'], 'source_reference' => ['type' => ['string', 'null']], 'official_source_url' => ['type' => ['string', 'null']], 'evidence_examples' => ['type' => 'array', 'items' => ['type' => 'object']], 'framework_mappings' => ['type' => 'array', 'items' => ['type' => 'object']], 'url' => ['type' => 'string', 'format' => 'uri']]],
        ],
    ],
];
