<?php

// Filter vocabularies and licence text for /guides, plus the initial free tools that
// database/seeders/ToolSeeder.php loads once into the `tools` table (files copied from
// resources/downloads/<slug>/ to the private disk). After seeding, manage tools in
// Admin → Tool library; edits here do not overwrite database rows.
return [
    'types' => ['guide' => 'Guide', 'template' => 'Template', 'checklist' => 'Checklist', 'register' => 'Register'],
    'frameworks' => ['eu-ai-act' => 'EU AI Act', 'iso-42001' => 'ISO/IEC 42001', 'nist-ai-rmf' => 'NIST AI RMF'],
    'topics' => ['inventory' => 'Inventory', 'risk' => 'Risk', 'incident' => 'Incident', 'governance' => 'Governance', 'evidence' => 'Evidence'],
    'license' => 'Templates are provided under CC BY 4.0 for use inside your organisation. They are informational resources, not legal advice, and completing one does not make an organisation compliant with any law or standard.',

    // Tags for the editorial guides in config/content.php so they share the same filters.
    'guide_tags' => [
        'ai-startup-eu-ai-act-readiness' => ['frameworks' => ['eu-ai-act'], 'topics' => ['governance', 'inventory', 'evidence'], 'featured' => true],
        'ai-governance-for-startups' => ['frameworks' => ['nist-ai-rmf', 'iso-42001'], 'topics' => ['governance', 'risk'], 'featured' => true],
        'iso-42001-vs-eu-ai-act' => ['frameworks' => ['iso-42001', 'eu-ai-act'], 'topics' => ['governance', 'evidence'], 'featured' => true],
        'nist-ai-rmf-vs-eu-ai-act' => ['frameworks' => ['nist-ai-rmf', 'eu-ai-act'], 'topics' => ['governance', 'risk'], 'featured' => true],
    ],

    'tools' => [
        'ai-system-inventory-template' => [
            'title' => 'AI System Inventory Template',
            'type' => 'template',
            'version' => '1.0',
            'updated' => '2026-09-11',
            'featured' => true,
            'short' => 'Track your AI systems, owners, models, vendors, data use, risk level, review dates and governance evidence in one register.',
            'purpose' => 'An inventory is the first artefact every AI governance framework asks for: the EU AI Act needs it to classify systems by risk and role, ISO/IEC 42001 expects an inventory of AI systems within scope, and the NIST AI RMF MAP function starts from knowing what is deployed. This template gives one row per AI system with the fields reviewers and auditors ask about.',
            'frameworks' => ['eu-ai-act', 'iso-42001', 'nist-ai-rmf'],
            'topics' => ['inventory', 'governance', 'evidence'],
            'fields' => [
                ['System ID', 'Stable identifier (e.g. AIS-001).'], ['System name', 'Product or internal name.'], ['Business owner', 'Accountable person or team.'], ['Technical owner', 'Team that builds or operates it.'],
                ['Purpose and use case', 'What decision or output it produces and for whom.'], ['Our role', 'Provider, deployer, importer, distributor or downstream integrator (EU AI Act terms).'],
                ['Model / vendor', 'Underlying model(s) and supplier, including general-purpose models.'], ['Data used', 'Personal data, special categories, training vs inference data.'],
                ['Affected people', 'Customers, employees, applicants, public.'], ['Markets', 'Jurisdictions where it is placed on the market or used.'],
                ['EU AI Act risk category', 'Prohibited, high-risk (Annex I/III), transparency, minimal, or not assessed.'], ['Other applicable rules', 'Sector rules, state laws, data-protection duties.'],
                ['Human oversight', 'How a person can intervene or override.'], ['Status', 'Idea, pilot, production, retired.'], ['Last review date', 'Date of the last governance review.'], ['Next review date', 'Planned review.'],
                ['Evidence links', 'Where documentation, tests and approvals live.'],
            ],
            'instructions' => ['Add one row per AI system, including third-party tools with AI features.', 'Decide your role per system before classifying risk; obligations differ by role.', 'Link evidence rather than pasting it, so the inventory stays a register.', 'Review at least quarterly and whenever a system changes purpose, data or market.'],
            'related_guides' => ['ai-startup-eu-ai-act-readiness', 'ai-governance-for-startups'],
            'related_policies' => ['eu-ai-act', 'us-nist-ai-rmf'],
            'next' => 'ai-risk-register-template',
            'files' => [['ai-system-inventory-template.xlsx', 'XLSX'], ['ai-system-inventory-template.csv', 'CSV'], ['ai-system-inventory-template.md', 'Markdown']],
        ],
        'ai-risk-register-template' => [
            'title' => 'AI Risk Register Template',
            'type' => 'register',
            'version' => '1.0',
            'updated' => '2026-09-11',
            'featured' => true,
            'short' => 'Record AI-specific risks per system with likelihood, impact, owner, controls and review dates, mapped to the MIT AI Risk Repository domains.',
            'purpose' => 'A risk register turns "we thought about risk" into evidence. The NIST AI RMF MEASURE and MANAGE functions, the ISO/IEC 42001 risk assessment clauses and the EU AI Act risk-management system (Article 9) all expect identified risks, evaluated severity, chosen treatments and monitoring. The register uses the seven MIT AI Risk Repository domains so entries can be compared with recorded incidents.',
            'frameworks' => ['nist-ai-rmf', 'iso-42001', 'eu-ai-act'],
            'topics' => ['risk', 'governance', 'evidence'],
            'fields' => [
                ['Risk ID', 'Stable identifier (e.g. R-001).'], ['System ID', 'Link to the inventory row.'], ['Risk domain', 'One of the seven MIT AI Risk Repository domains.'], ['Risk description', 'What could go wrong, for whom, how.'],
                ['Causal entity / intent / timing', 'Human or AI; intentional or unintentional; pre- or post-deployment.'], ['Likelihood (1-5)', 'Estimated chance in the review period.'], ['Impact (1-5)', 'Severity for people, the organisation or society.'],
                ['Inherent score', 'Likelihood × impact before controls.'], ['Existing controls', 'Technical, procedural or contractual controls in place.'], ['Residual score', 'Score after controls.'],
                ['Treatment', 'Accept, mitigate, transfer or avoid.'], ['Action and owner', 'What will be done and who is accountable.'], ['Due date', 'When the action completes.'], ['Monitoring signal', 'Metric, log or test that shows the risk is under control.'],
                ['Related obligation', 'Legal or standard clause the control satisfies.'], ['Last reviewed', 'Date.'], ['Status', 'Open, in progress, closed.'],
            ],
            'instructions' => ['Start from the inventory: every production system needs at least one entry per relevant domain.', 'Use recorded incidents on this site to challenge your likelihood estimates.', 'Keep residual scores honest; an all-green register is a warning sign for reviewers.', 'Review after every incident and at the cadence your policy sets.'],
            'related_guides' => ['ai-governance-for-startups', 'nist-ai-rmf-vs-eu-ai-act'],
            'related_policies' => ['us-nist-ai-rmf', 'eu-ai-act'],
            'next' => 'eu-ai-act-readiness-checklist',
            'files' => [['ai-risk-register-template.xlsx', 'XLSX'], ['ai-risk-register-template.csv', 'CSV'], ['ai-risk-register-template.md', 'Markdown']],
        ],
        'eu-ai-act-readiness-checklist' => [
            'title' => 'EU AI Act Readiness Checklist',
            'type' => 'checklist',
            'version' => '1.0',
            'updated' => '2026-09-11',
            'featured' => true,
            'short' => 'A dated checklist from inventory and role to high-risk workstreams, general-purpose AI duties and evidence, tied to the obligations recorded on this site.',
            'purpose' => 'The EU AI Act applies in phases (prohibitions and literacy since February 2025, general-purpose AI duties since August 2025, most high-risk obligations from August 2026). This checklist orders the work so that documentation is produced as a by-product of engineering and links each item to the recorded obligation and its official source.',
            'frameworks' => ['eu-ai-act'],
            'topics' => ['governance', 'evidence', 'inventory'],
            'fields' => [
                ['Phase', 'Foundations, prohibited practices, classification, high-risk workstreams, GPAI, transparency, evidence.'], ['Item', 'The concrete step.'], ['Obligation reference', 'Article or recorded obligation slug.'], ['Applies to', 'Provider, deployer, GPAI provider.'],
                ['Owner', 'Accountable person.'], ['Due', 'Target date, aligned with the application dates.'], ['Status', 'Not started, in progress, done, not applicable.'], ['Evidence', 'Link to the artefact.'],
            ],
            'instructions' => ['Mark items not applicable with a one-line reason; reviewers read those first.', 'Use the application dates on the EU AI Act record to set due dates.', 'Attach evidence links, not descriptions.'],
            'related_guides' => ['ai-startup-eu-ai-act-readiness', 'eu-ai-act'],
            'related_policies' => ['eu-ai-act'],
            'next' => 'ai-incident-response-checklist',
            'files' => [['eu-ai-act-readiness-checklist.md', 'Markdown'], ['eu-ai-act-readiness-checklist.csv', 'CSV'], ['eu-ai-act-readiness-checklist.xlsx', 'XLSX'], ['eu-ai-act-readiness-checklist.docx', 'DOCX']],
        ],
        'ai-incident-response-checklist' => [
            'title' => 'AI Incident Response Checklist',
            'type' => 'checklist',
            'version' => '1.0',
            'updated' => '2026-09-11',
            'featured' => false,
            'short' => 'Detect, triage, contain, report and learn from AI incidents, including the serious-incident reporting duties in the EU AI Act.',
            'purpose' => 'AI incidents differ from ordinary outages: harm can be silent, distributed and discovered by users or journalists first. This checklist sets out detection signals, severity triage using the MIT AI Risk Repository domains, containment options (rollback, kill switch, human-only mode), regulatory reporting (EU AI Act Article 73 serious incidents, data-protection breach rules) and the post-incident review that feeds the risk register.',
            'frameworks' => ['eu-ai-act', 'nist-ai-rmf', 'iso-42001'],
            'topics' => ['incident', 'governance', 'risk'],
            'fields' => [
                ['Stage', 'Prepare, detect, triage, contain, notify, recover, learn.'], ['Item', 'The concrete step.'], ['Owner', 'Role responsible.'], ['Time target', 'Expected time from detection.'], ['Reference', 'Obligation, standard clause or internal policy.'], ['Done', 'Yes / no / n.a. with timestamp.'],
            ],
            'instructions' => ['Run a tabletop exercise with a recorded incident from the AI Incident Database before you need this for real.', 'Keep the notification matrix current: regulator, customers, data-protection authority, insurer.', 'Every incident closes with a risk-register update.'],
            'related_guides' => ['ai-governance-for-startups'],
            'related_policies' => ['eu-ai-act'],
            'next' => 'ai-governance-30-day-starter-plan',
            'files' => [['ai-incident-response-checklist.md', 'Markdown'], ['ai-incident-response-checklist.csv', 'CSV'], ['ai-incident-response-checklist.xlsx', 'XLSX'], ['ai-incident-response-checklist.docx', 'DOCX']],
        ],
        'ai-governance-30-day-starter-plan' => [
            'title' => 'AI Governance 30-Day Starter Plan',
            'type' => 'guide',
            'version' => '1.0',
            'updated' => '2026-09-11',
            'featured' => false,
            'short' => 'A week-by-week plan for a small team to stand up AI governance: inventory, roles, policy, risk register, incident process and first evidence pack.',
            'purpose' => 'Most teams stall because governance looks like a year-long programme. This plan front-loads the four artefacts that regulators, customers and auditors ask for first, using the NIST AI RMF GOVERN, MAP, MEASURE and MANAGE functions as the backbone and pointing to the free templates on this site.',
            'frameworks' => ['nist-ai-rmf', 'iso-42001'],
            'topics' => ['governance', 'inventory', 'risk', 'incident'],
            'fields' => [
                ['Week', '1 to 4, plus a day-30 review.'], ['Goal', 'Outcome for the week.'], ['Tasks', 'Concrete steps with the template to use.'], ['Output', 'The artefact produced.'], ['NIST AI RMF function', 'Govern, Map, Measure or Manage.'],
            ],
            'instructions' => ['Assign one owner for the 30 days with a few hours a week.', 'Use the inventory and risk register templates in weeks 1 and 2.', 'Book the day-30 review with leadership before you start.'],
            'related_guides' => ['ai-governance-for-startups', 'nist-ai-rmf-vs-eu-ai-act'],
            'related_policies' => ['us-nist-ai-rmf'],
            'next' => 'ai-system-inventory-template',
            'files' => [['ai-governance-30-day-starter-plan.md', 'Markdown'], ['ai-governance-30-day-starter-plan.csv', 'CSV'], ['ai-governance-30-day-starter-plan.docx', 'DOCX']],
        ],
    ],
];
