@extends('site.layouts.app')
@section('content')
<div class="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8 py-8">
    <x-site.breadcrumbs :items="$seo->breadcrumbs" />
    <h1 class="mt-2 text-2xl sm:text-3xl font-semibold tracking-tight text-slate-900">About AIPolicyTracker</h1>
    <p class="mt-3 prose-policy">{{ config('aipolicytracker.positioning') }} It is an open, source-backed AI policy and regulatory intelligence platform for founders, product leaders, compliance and legal teams, policy professionals, developers, investors, journalists, governments and development organisations.</p>
    <section class="mt-8" aria-labelledby="mission-heading"><h2 id="mission-heading" class="section-title">Mission</h2><p class="prose-policy mt-2">Make AI policy legible and actionable. Most teams do not need another summary of the news; they need to know what is binding, for whom, from when, and what evidence a reasonable compliance programme would produce. We structure that from official sources, show the verification state honestly, and publish the data openly so others can build on it.</p><p class="prose-policy mt-2">The initial geographic focus is the EU, UK, US, India, Nepal, Singapore, Australia and the UAE, expanding across South Asia, ASEAN, Africa, Latin America and other emerging markets as reviewers join.</p></section>
    <section class="mt-8" aria-labelledby="maintainers-heading"><h2 id="maintainers-heading" class="section-title">Maintainers</h2><ul class="mt-2 space-y-1.5 text-sm text-slate-700">@foreach($maintainers as $m)<li><a href="{{ $m['url'] }}" rel="noopener" class="font-medium text-slate-900">{{ $m['name'] }}</a> — {{ $m['role'] }}</li>@endforeach</ul></section>
    <section class="mt-8" aria-labelledby="reviewers-heading"><h2 id="reviewers-heading" class="section-title">Advisory and reviewer invitation</h2><p class="prose-policy mt-2">We are recruiting reviewers with legal, policy or compliance expertise in specific jurisdictions to verify records against official sources. Reviewers are credited on the records they verify (where they wish to be) and help set editorial standards. Time commitment is flexible; verification of a single record typically takes under an hour.</p><a href="{{ route('contribute', ['type' => 'reviewer_application']) }}" class="btn-primary mt-3">Volunteer as a reviewer</a></section>
    <section class="mt-8" aria-labelledby="contact-heading"><h2 id="contact-heading" class="section-title">Contact</h2><p class="prose-policy mt-2">@if($contacts)Email @foreach($contacts as $c)<a href="mailto:{{ $c }}">{{ $c }}</a>@if(!$loop->last), @endif @endforeach. @endif Open an issue or pull request on <a href="{{ config('aipolicytracker.github_url') }}" rel="noopener" data-track="github_click">GitHub</a> for data corrections and feature requests. Security issues: see the repository's SECURITY.md.</p></section>
    <section class="mt-8" aria-labelledby="certifyi-heading"><h2 id="certifyi-heading" class="section-title">Relationship to Certifyi</h2><p class="prose-policy mt-2">AIPolicyTracker is maintained by the team behind <a href="{{ config('aipolicytracker.certifyi_url') }}" rel="noopener" data-track="certifyi_click">Certifyi</a>, a separate compliance execution platform. The two are distinct: AIPolicyTracker is the public, open intelligence layer with open data and an open-source codebase; Certifyi is a commercial product for turning obligations into compliance workflows. Nothing on this site requires a Certifyi account, and the data licence does not change based on how you use it.</p></section>
    <x-site.disclaimer class="mt-8" />
</div>
@endsection
