@extends('site.layouts.app')
@section('content')
<div class="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8 py-8">
    <x-site.breadcrumbs :items="$seo->breadcrumbs" />
    <h1 class="mt-2 text-2xl sm:text-3xl font-semibold tracking-tight text-brand-navy">Methodology</h1>
    <p class="mt-3 prose-policy">{{ config('aipolicytracker.trust_statement') }} This page explains how records are sourced, structured, reviewed and kept current, and what the site does not do.</p>

    <section class="mt-8" aria-labelledby="principles-heading"><h2 id="principles-heading" class="section-title">Editorial and source-verification principles</h2><ul class="mt-2 list-disc pl-5 space-y-1.5 text-sm text-brand-body">
        <li><span class="font-medium text-brand-navy">Primary sources first.</span> Every record links to an official document or page. Secondary sources are used only when clearly labelled and never as the sole basis for a legal claim.</li>
        <li><span class="font-medium text-brand-navy">No invention.</span> If a date, penalty, obligation or outcome cannot be established from the source, the field is left empty and the confidence level is set to "unavailable". We never fill gaps with assumptions.</li>
        <li><span class="font-medium text-brand-navy">Original summaries.</span> Summaries are written in plain language with article or section references. We do not reproduce copyrighted legal commentary, paid database content or standards text such as ISO/IEC documents.</li>
        <li><span class="font-medium text-brand-navy">Visible uncertainty.</span> Proposed laws, differing application dates, pending amendments and unconfirmed facts are labelled as such in the record and on the page.</li>
        <li><span class="font-medium text-brand-navy">Human verification.</span> A record is marked verified only when a named reviewer has opened the official source and confirmed each field. Until then it shows "human verification pending".</li>
        <li><span class="font-medium text-brand-navy">Not legal advice.</span> Content is informational. It is not a substitute for advice from qualified counsel in the relevant jurisdiction.</li>
    </ul></section>

    <section class="mt-8" aria-labelledby="hierarchy-heading"><h2 id="hierarchy-heading" class="section-title">Source-of-truth hierarchy</h2><ol class="mt-2 list-decimal pl-5 space-y-1 text-sm text-brand-body">@foreach($tiers as $n => $label)<li><span class="font-medium text-brand-navy">Tier {{ $n }}:</span> {{ $label }}</li>@endforeach</ol></section>

    <section class="mt-8" aria-labelledby="model-heading"><h2 id="model-heading" class="section-title">Data model and taxonomy</h2><p class="prose-policy mt-2">A jurisdiction holds policy instruments. An instrument has versions, sections, obligations, applicability rules, deadlines, enforcement events, procurement rules and source documents. Obligations carry evidence examples and original framework mappings. Change events record dated developments. Controlled vocabularies cover {{ implode(', ', array_map('strtolower', array_values($taxonomies))) }}. The full schema is documented on the <a href="{{ route('open-data') }}">open data</a> page and in the repository.</p></section>

    <section class="mt-8" aria-labelledby="review-heading"><h2 id="review-heading" class="section-title">Review levels</h2><div class="table-wrap mt-3"><table><caption class="sr-only">Review statuses</caption><thead><tr><th scope="col">Review status</th><th scope="col">Meaning</th></tr></thead><tbody>@foreach($reviewStatuses as $r)<tr><td class="font-mono text-xs whitespace-nowrap">{{ $r->value }}</td><td>{{ $r->label() }}</td></tr>@endforeach</tbody></table></div><p class="mt-2 text-sm text-brand-muted">Confidence levels (high, medium, low, unavailable) describe how directly the record is supported by the identified source, independently of whether a human has yet verified it.</p></section>

    <section class="mt-8" aria-labelledby="status-heading"><h2 id="status-heading" class="section-title">Policy status definitions</h2><div class="table-wrap mt-3"><table><caption class="sr-only">Policy statuses</caption><thead><tr><th scope="col">Status</th><th scope="col">Definition</th></tr></thead><tbody>@foreach($statuses as $s)<tr><td class="whitespace-nowrap"><x-site.status-badge :status="$s" /></td><td>{{ $s->definition() }}</td></tr>@endforeach</tbody></table></div></section>

    <section class="mt-8" aria-labelledby="changes-heading"><h2 id="changes-heading" class="section-title">How changes are detected and reviewed</h2><p class="prose-policy mt-2">Maintainers and contributors monitor official journals, legislature and regulator websites, consultation portals and government press releases for the covered jurisdictions. Each development is recorded as a change event with its date, source, practical impact and impact level (urgent, high, routine), then reviewed before publication. Records affected by a change are re-verified and their content version incremented. The <a href="{{ route('changes.index') }}">change log</a> and its RSS feed are the public record of this process; the repository history shows every edit.</p></section>

    <section class="mt-8" aria-labelledby="limits-heading"><h2 id="limits-heading" class="section-title">Known limitations</h2><ul class="mt-2 list-disc pl-5 space-y-1.5 text-sm text-brand-body"><li>Coverage is deliberately narrow and deep: a small number of jurisdictions with structured records rather than a broad but shallow list.</li><li>Many records are still pending human verification; the verification line on each page tells you which.</li><li>Some official documents are available only in local languages or without stable URLs; such records say so in their source reference.</li><li>Framework mappings to ISO/IEC 42001 and the NIST AI RMF are original editorial judgements with stated confidence, not official crosswalks.</li><li>Application dates can change after enactment; a record is only as current as its last verification.</li></ul></section>

    <section class="mt-8" aria-labelledby="ai-heading"><h2 id="ai-heading" class="section-title">Disclosure of AI assistance</h2><p class="prose-policy mt-2">AI tools may be used to help draft summaries, structure records and detect changes. Every published record must still link to an official source and pass human review before it is marked verified; AI output is never published as verified fact on its own. The initial dataset was drafted with AI assistance and is labelled "pending review" until reviewers complete verification.</p></section>
    <x-site.disclaimer class="mt-8" />
</div>
@endsection
