@extends('site.layouts.app')
@section('content')
<div class="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8 py-8">
    <x-site.breadcrumbs :items="$seo->breadcrumbs" />
    <h1 class="mt-2 text-2xl sm:text-3xl font-semibold tracking-tight text-brand-navy">Open AI policy dataset, schema and API</h1>
    <p class="mt-3 prose-policy">AIPolicyTracker publishes its policy records as open data under {{ config('aipolicytracker.data_license') }}. The dataset currently holds {{ $stats['jurisdictions'] }} jurisdictions, {{ $stats['policies'] }} policy instruments, {{ $stats['obligations'] }} obligations and {{ $stats['changes'] }} change events @if($lastUpdated), last updated {{ $lastUpdated->format('j F Y') }}@endif. Every record carries an official source URL, review status, confidence level and verification dates so you can judge it before you use it.</p>
    <div class="mt-5 flex flex-wrap gap-2"><a href="{{ route('open-data.download') }}" class="btn-primary" data-track="dataset_download">Download latest JSON bundle</a><a href="{{ url('/api/v1') }}" class="btn-secondary" data-track="api_docs_view">API root</a><a href="{{ route('openapi') }}" class="btn-secondary">OpenAPI specification</a><a href="{{ config('aipolicytracker.github_url') }}" rel="noopener" class="btn-secondary" data-track="github_click">GitHub repository</a></div>

    <section class="mt-10" aria-labelledby="desc-heading"><h2 id="desc-heading" class="section-title">Dataset description</h2>
        <p class="prose-policy mt-2">Record types: jurisdiction, policy instrument, policy version, section, obligation, applicability rule, deadline, enforcement event, procurement rule, framework mapping, evidence artifact, change event and source document, plus controlled vocabularies for {{ implode(', ', array_map('strtolower', array_values($taxonomies))) }}. Summaries are original plain-language descriptions; no copyrighted commentary or standards text is included.</p></section>

    <section class="mt-8" aria-labelledby="schema-heading"><h2 id="schema-heading" class="section-title">Schema documentation</h2>
        <p class="prose-policy mt-2">Records are validated against JSON Schema (draft 2020-12) before import. Each schema is served at the URL its own <code class="rounded bg-brand-paper px-1">$id</code> declares, so a validator can resolve it: @foreach($schemaFiles as $file)<a class="font-mono text-xs" href="{{ route('schema.show', str_replace('.schema.json', '', $file)) }}">{{ $file }}</a>@if(! $loop->last) · @endif @endforeach. Version {{ config('aipolicytracker.data_schema_version') }}.</p>
        <div class="table-wrap mt-3"><table><caption class="sr-only">Data-quality fields</caption><thead><tr><th scope="col">Field</th><th scope="col">Meaning</th></tr></thead><tbody>
            @foreach(['official_source_url' => 'Primary official document or page the record is based on', 'source_title / source_publisher / source_document_date' => 'Bibliographic details of that source', 'source_reference' => 'Article, section or page reference inside the source', 'source_tier' => '1 official primary; 2 official guidance/consultation; 3 labelled secondary; 4 community submission', 'last_checked_at' => 'When a maintainer last opened the source', 'last_verified_at' => 'When a human reviewer confirmed the record against the source', 'review_status' => 'draft, pending_review, verified or needs_update', 'confidence_level' => 'high, medium, low or unavailable', 'content_version / change_summary' => 'Record version and what changed in it', 'reviewed_by' => 'Reviewer name or handle, when safe to expose'] as $f => $m)<tr><td class="font-mono text-xs whitespace-nowrap">{{ $f }}</td><td>{{ $m }}</td></tr>@endforeach
        </tbody></table></div></section>

    <section class="mt-8" aria-labelledby="bulk-heading"><h2 id="bulk-heading" class="section-title">Bulk exports and per-record context files</h2>
        <p class="prose-policy mt-2">The bundle above is one nested document you load whole. These are the other shape: one self-contained row or file at a time, for a spreadsheet, a pipeline or a model's context window. Every row and every file carries its own provenance — official source, review status, confidence and the date the facts were last confirmed — because a record that travels on its own without them invites somebody to treat an unverified summary as a fact.</p>
        <div class="table-wrap mt-3"><table><caption class="sr-only">Bulk exports</caption><thead><tr><th scope="col">Dataset</th><th scope="col">Formats</th></tr></thead><tbody>
            @foreach(\App\Services\MachineReadable\BulkExport::DATASETS as $key => $meta)<tr><td>{{ $meta['label'] }}</td><td><a href="{{ route('open-data.csv', $key) }}">CSV</a> · <a href="{{ route('open-data.ndjson', $key) }}">NDJSON</a></td></tr>@endforeach
        </tbody></table></div>
        <p class="prose-policy mt-3">Per-record Markdown, one file an assistant can read without scraping a page: <code class="rounded bg-brand-paper px-1">/policies/{slug}.md</code>, <code class="rounded bg-brand-paper px-1">/jurisdictions/{slug}.md</code>, <code class="rounded bg-brand-paper px-1">/obligations/{slug}.md</code> and <code class="rounded bg-brand-paper px-1">/changes/{slug}.md</code> — for example <a href="{{ route('policies.context', 'eu-ai-act') }}">the EU AI Act as a context file</a>.</p>
        <p class="prose-policy mt-3"><a href="{{ route('open-data.health') }}">{{ url('/open-data/health.json') }}</a> reports in one document how far the corpus can be trusted right now: how many records are past their re-check date, how many are missing required fields and how many have been verified by a named reviewer. Read it before quoting a record as settled.</p>
        <h3 class="mt-6 font-display text-lg text-brand-navy">Agent server</h3>
        <p class="prose-policy mt-2">An assistant can query these surfaces directly through the Model Context Protocol server in the repository's <code class="rounded bg-brand-paper px-1">agent/</code> directory: read-only, unauthenticated, no dependencies. It offers the corpus health check first and repeats in every result that these records are structured summaries with links to official texts, not legal advice. See <a href="{{ config('aipolicytracker.github_url') }}" rel="noopener">the repository</a> for setup.</p>
    </section>

    <section class="mt-8" aria-labelledby="license-heading"><h2 id="license-heading" class="section-title">Data licence</h2><p class="prose-policy mt-2">Data: <a href="{{ config('aipolicytracker.data_license_url') }}" rel="license noopener">{{ config('aipolicytracker.data_license') }}</a>. Code: Apache-2.0. Official documents linked from records remain under their publishers' terms.</p></section>

    <section class="mt-8" aria-labelledby="api-heading"><h2 id="api-heading" class="section-title">API documentation</h2>
        <p class="prose-policy mt-2">Read-only, no authentication, rate limited (120 requests per minute per IP), cached for 10 minutes, CORS enabled. Base URL <code class="rounded bg-brand-paper px-1">{{ url('/api/v1') }}</code>.</p>
        <div class="table-wrap mt-3"><table><caption class="sr-only">Endpoints</caption><thead><tr><th scope="col">Endpoint</th><th scope="col">Description</th></tr></thead><tbody>
            @foreach(['/jurisdictions' => 'List published jurisdictions', '/jurisdictions/{slug}' => 'One jurisdiction with its policies', '/policies?q=&jurisdiction=&status=&sector=&use_case=&actor=&binding=&sort=' => 'Search and filter policy instruments (paginated)', '/policies/{slug}' => 'Full policy record with obligations, deadlines and sources', '/obligations?category=&jurisdiction=&binding=' => 'Search obligations', '/obligations/{slug}' => 'One obligation with mappings and evidence examples', '/changes?since=YYYY-MM-DD&jurisdiction=' => 'Change events, newest first', '/taxonomies' => 'Controlled vocabularies'] as $e => $d)<tr><td class="font-mono text-xs break-all">{{ $e }}</td><td>{{ $d }}</td></tr>@endforeach
        </tbody></table></div>
        <h3 class="mt-6 font-display text-lg text-brand-navy">Third-party datasets (attribution required)</h3>
        <ul class="mt-2 text-sm space-y-1">
            <li>AI Incident Database, metadata for every incident (CC BY-SA 4.0): <a href="{{ route('risk.incidents.export', 'csv') }}">CSV</a> · <a href="{{ route('risk.incidents.export', 'json') }}">JSON</a> · <a href="{{ route('risk.incidents.browse') }}">browse</a></li>
            <li>MIT AI Risk Repository, risk database (CC BY 4.0): <a href="{{ route('risk.risks.export', 'csv') }}">CSV</a> · <a href="{{ route('risk.risks.export', 'json') }}">JSON</a> · <a href="{{ route('risk.risks') }}">browse</a></li>
            <li>MIT domain taxonomy with our use-case mapping: <a href="{{ url('/data/external/mit_ai_risk_domains.json') }}" onclick="return false" class="text-brand-muted">data/external/mit_ai_risk_domains.json in the repository</a></li>
        </ul>
        <p class="mt-2 text-sm text-brand-muted">Each policy page also exposes its record at <code class="rounded bg-brand-paper px-1">/policies/{slug}.json</code>, and the change log at <a href="{{ route('changes.feed') }}">RSS</a>.</p></section>

    <section class="mt-8" aria-labelledby="contrib-heading"><h2 id="contrib-heading" class="section-title">Contribution workflow</h2><ol class="mt-2 list-decimal pl-5 space-y-1 text-sm text-brand-body"><li>Fork the repository and edit or add a YAML record under <code class="rounded bg-brand-paper px-1">data/</code>.</li><li>Run <code class="rounded bg-brand-paper px-1">php artisan policy:validate</code>.</li><li>Open a pull request listing each changed field and its official source URL.</li><li>A reviewer verifies against the source and sets <code class="rounded bg-brand-paper px-1">review_status: verified</code>.</li><li>Merged records are imported and published. No web form can publish directly; see <a href="{{ route('contribute') }}">Contribute</a>.</li></ol></section>

    <section class="mt-8" aria-labelledby="releases-heading"><h2 id="releases-heading" class="section-title">Release history</h2><ul class="mt-2 space-y-1.5 text-sm text-brand-body">@foreach($releases as $r)<li><span class="font-mono">{{ $r['version'] }}</span> · {{ $r['date'] }} — {{ $r['notes'] }}</li>@endforeach</ul></section>

    <section class="mt-8" aria-labelledby="cite-heading"><h2 id="cite-heading" class="section-title">Citation guidance</h2><p class="prose-policy mt-2">Cite the specific record URL and the date you accessed it, and cite the official source alongside it. Suggested format:</p><pre class="mt-2 overflow-x-auto rounded-sm bg-brand-navy p-3 text-xs text-white/80">{{ config('aipolicytracker.citation') }}</pre><p class="mt-2 text-sm text-brand-muted">For AI assistants and crawlers, see <a href="{{ route('llms') }}">/llms.txt</a> and <a href="{{ route('llms.full') }}">/llms-full.txt</a>.</p></section>
    <x-site.disclaimer class="mt-8" />
</div>
@endsection
