@extends('site.layouts.app')
@section('content')
<div class="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8 py-8">
    <x-site.breadcrumbs :items="$seo->breadcrumbs" />
    <h1 class="mt-2 text-2xl sm:text-3xl font-semibold tracking-tight text-slate-900">Open AI policy dataset, schema and API</h1>
    <p class="mt-3 prose-policy">AIPolicyTracker publishes its policy records as open data under {{ config('aipolicytracker.data_license') }}. The dataset currently holds {{ $stats['jurisdictions'] }} jurisdictions, {{ $stats['policies'] }} policy instruments, {{ $stats['obligations'] }} obligations and {{ $stats['changes'] }} change events @if($lastUpdated), last updated {{ $lastUpdated->format('j F Y') }}@endif. Every record carries an official source URL, review status, confidence level and verification dates so you can judge it before you use it.</p>
    <div class="mt-5 flex flex-wrap gap-2"><a href="{{ route('open-data.download') }}" class="btn-primary" data-track="dataset_download">Download latest JSON bundle</a><a href="{{ url('/api/v1') }}" class="btn-secondary" data-track="api_docs_view">API root</a><a href="{{ route('openapi') }}" class="btn-secondary">OpenAPI specification</a><a href="{{ config('aipolicytracker.github_url') }}" rel="noopener" class="btn-secondary" data-track="github_click">GitHub repository</a></div>

    <section class="mt-10" aria-labelledby="desc-heading"><h2 id="desc-heading" class="section-title">Dataset description</h2>
        <p class="prose-policy mt-2">Record types: jurisdiction, policy instrument, policy version, section, obligation, applicability rule, deadline, enforcement event, procurement rule, framework mapping, evidence artifact, change event and source document, plus controlled vocabularies for {{ implode(', ', array_map('strtolower', array_values($taxonomies))) }}. Summaries are original plain-language descriptions; no copyrighted commentary or standards text is included.</p></section>

    <section class="mt-8" aria-labelledby="schema-heading"><h2 id="schema-heading" class="section-title">Schema documentation</h2>
        <p class="prose-policy mt-2">Records are validated against JSON Schema (draft 2020-12) before import. Schema files in the repository's <code class="rounded bg-slate-100 px-1">data/schema</code> directory: {{ implode(', ', $schemaFiles) }}. Version {{ config('aipolicytracker.data_schema_version') }}.</p>
        <div class="table-wrap mt-3"><table><caption class="sr-only">Data-quality fields</caption><thead><tr><th scope="col">Field</th><th scope="col">Meaning</th></tr></thead><tbody>
            @foreach(['official_source_url' => 'Primary official document or page the record is based on', 'source_title / source_publisher / source_document_date' => 'Bibliographic details of that source', 'source_reference' => 'Article, section or page reference inside the source', 'source_tier' => '1 official primary; 2 official guidance/consultation; 3 labelled secondary; 4 community submission', 'last_checked_at' => 'When a maintainer last opened the source', 'last_verified_at' => 'When a human reviewer confirmed the record against the source', 'review_status' => 'draft, pending_review, verified or needs_update', 'confidence_level' => 'high, medium, low or unavailable', 'content_version / change_summary' => 'Record version and what changed in it', 'reviewed_by' => 'Reviewer name or handle, when safe to expose'] as $f => $m)<tr><td class="font-mono text-xs whitespace-nowrap">{{ $f }}</td><td>{{ $m }}</td></tr>@endforeach
        </tbody></table></div></section>

    <section class="mt-8" aria-labelledby="license-heading"><h2 id="license-heading" class="section-title">Data licence</h2><p class="prose-policy mt-2">Data: <a href="{{ config('aipolicytracker.data_license_url') }}" rel="license noopener">{{ config('aipolicytracker.data_license') }}</a>. Code: Apache-2.0. Official documents linked from records remain under their publishers' terms.</p></section>

    <section class="mt-8" aria-labelledby="api-heading"><h2 id="api-heading" class="section-title">API documentation</h2>
        <p class="prose-policy mt-2">Read-only, no authentication, rate limited (120 requests per minute per IP), cached for 10 minutes, CORS enabled. Base URL <code class="rounded bg-slate-100 px-1">{{ url('/api/v1') }}</code>.</p>
        <div class="table-wrap mt-3"><table><caption class="sr-only">Endpoints</caption><thead><tr><th scope="col">Endpoint</th><th scope="col">Description</th></tr></thead><tbody>
            @foreach(['/jurisdictions' => 'List published jurisdictions', '/jurisdictions/{slug}' => 'One jurisdiction with its policies', '/policies?q=&jurisdiction=&status=&sector=&use_case=&actor=&binding=&sort=' => 'Search and filter policy instruments (paginated)', '/policies/{slug}' => 'Full policy record with obligations, deadlines and sources', '/obligations?category=&jurisdiction=&binding=' => 'Search obligations', '/obligations/{slug}' => 'One obligation with mappings and evidence examples', '/changes?since=YYYY-MM-DD&jurisdiction=' => 'Change events, newest first', '/taxonomies' => 'Controlled vocabularies'] as $e => $d)<tr><td class="font-mono text-xs break-all">{{ $e }}</td><td>{{ $d }}</td></tr>@endforeach
        </tbody></table></div>
        <p class="mt-2 text-sm text-slate-600">Each policy page also exposes its record at <code class="rounded bg-slate-100 px-1">/policies/{slug}.json</code>, and the change log at <a href="{{ route('changes.feed') }}">RSS</a>.</p></section>

    <section class="mt-8" aria-labelledby="contrib-heading"><h2 id="contrib-heading" class="section-title">Contribution workflow</h2><ol class="mt-2 list-decimal pl-5 space-y-1 text-sm text-slate-700"><li>Fork the repository and edit or add a YAML record under <code class="rounded bg-slate-100 px-1">data/</code>.</li><li>Run <code class="rounded bg-slate-100 px-1">php artisan policy:validate</code>.</li><li>Open a pull request listing each changed field and its official source URL.</li><li>A reviewer verifies against the source and sets <code class="rounded bg-slate-100 px-1">review_status: verified</code>.</li><li>Merged records are imported and published. No web form can publish directly; see <a href="{{ route('contribute') }}">Contribute</a>.</li></ol></section>

    <section class="mt-8" aria-labelledby="releases-heading"><h2 id="releases-heading" class="section-title">Release history</h2><ul class="mt-2 space-y-1.5 text-sm text-slate-700">@foreach($releases as $r)<li><span class="font-mono">{{ $r['version'] }}</span> · {{ $r['date'] }} — {{ $r['notes'] }}</li>@endforeach</ul></section>

    <section class="mt-8" aria-labelledby="cite-heading"><h2 id="cite-heading" class="section-title">Citation guidance</h2><p class="prose-policy mt-2">Cite the specific record URL and the date you accessed it, and cite the official source alongside it. Suggested format:</p><pre class="mt-2 overflow-x-auto rounded-md bg-slate-900 p-3 text-xs text-slate-100">{{ config('aipolicytracker.citation') }}</pre><p class="mt-2 text-sm text-slate-600">For AI assistants and crawlers, see <a href="{{ route('llms') }}">/llms.txt</a> and <a href="{{ route('llms.full') }}">/llms-full.txt</a>.</p></section>
    <x-site.disclaimer class="mt-8" />
</div>
@endsection
